---
abstract: 'Manage configuration files with YAML and variable references.'
author:
  - "Matthew O'Connor <matthew@canonical.org>"
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-AppConfig
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=YAML-AppConfig
  repository: git://github.com/Xaerxess/YAML-AppConfig.git
version: 0.18
