---
abstract: 'Manage configuration files with YAML and variable references.'
author:
  - "Matthew O'Connor <matthew@canonical.org>"
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YAML-AppConfig
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Storable: '0'
  YAML: '0.38'
  perl: '5.006000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=YAML-AppConfig
  repository: git://github.com/Xaerxess/YAML-AppConfig.git
version: '0.19'
