---
abstract: 'Manage config files with YAML and variable references.'
author:
  - "Matthew O'Connor <matthew@canonical.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-AppConfig
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Storable: 0
  UNIVERSAL: 0
  YAML: 0.38
version: 0.17
